[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "mo"
version = "0.0.3"
requires-python = "~= 3.9"
dependencies = [
    "requests",
    "iterfzf",
    "cookiecutter"
]

[project.scripts]
mo = "mo.main:main"

[tool.poe.tasks]
run = "mo"
